### ISSUE TITLE
The naming of the Mercator variants in Projection Engine

### ISSUE THREAD

**Issue by phaarnes** [Esri/projection-engine-db-doc#48]
Hi,

This is probably more of a question than an issue.

According to the ESRI PE documentation, the "Mercator Variant C" projection should have the name "Mercator_Variant_C" in ESRI WKT. 
See the file [pe_list_projection.txt](https://github.com/Esri/projection-engine-db-doc/blob/master/text/pe_list_projection.txt) for example.
However in ArcGIS PRO this method is named only "Mercator". And if  "Mercator_Variant_C" is used in Petrel, it just crashes.
I also see this for the other Mercator variants as well. Take [Pulkovo 1942 / Caspian Sea Mercator (EPSG:3388)](https://epsg.org/crs_3388/Pulkovo-1942-Caspian-Sea-Mercator.html?sessionkey=ml20djhha8) for instance. It uses Mercator variant B, but according to pe_list_projcs.txt, the name "Mercator” should be used in the WKT.  

At the [ArcGIS web page](https://pro.arcgis.com/en/pro-app/latest/help/mapping/properties/mercator.htm), it says that the same algorithm is used for all these tree variants.

Is the «best practice” to use only “Mercator” in the WKT regardless of the variant? Or is it an update that has not yet been fully implemented in all stages? Will the use of only "Mercator" in ESRI WKT create problems in the future?

**Comment by beuan** [comment]
Hi @phaarnes! 

ArcGIS and the Projection Engine can recognize definitions for all Mercator variants and correctly read them from WKT and WKT2 strings. When objects are created using these strings, we output them with the same names. If a CRS definition is created using WKID, we use our “canonical” name, which in this case is `Mercator`. I am unsure what libraries Petrel software uses to read and process CRS definitions.

The term `Mercator` is synonymous with `Mercator (variant B)`, `Mercator_Variant_B`, and `Mercator Variant B`. This was the original Mercator in the Projection Engine, and we need to retain this name for backward compatibility and interoperability with older versions of ArcGIS software, as well as with the numerous strings already in public use that employ this standalone term without a variant qualifier. 

It is not a good idea to use "Mercator" for all three variants because they use different parameters. For instance, variant A requires a Scale Factor parameter, variant B needs a Standard Parallel 1 parameter, and variant C a Latitude of Origin parameter. It is better to be specific in the variant A and C cases. Using variant B would not hurt either, especially when working outside the ArcGIS environment. 

Currently, there appears to be no PROJCRS in the EPSG database that utilizes Mercator Variant C as their conversion method. Consequently, the Projection Engine does not have any definitions using this variant, but it should work with a custom definitions.

I hope this helps!

**Comment by phaarnes** [comment]
Hi,

Thank you for your thorough answer!
