### ISSUE TITLE
Inconsistent use of the "GCS_" and "D_" prefixes

### ISSUE THREAD

**Issue by phaarnes** [Esri/projection-engine-db-doc#61]
Hi,

 Almost all of your geographic CRSs have the `GCS_` prefix, and the datums have the `D_` prefix. However, I have stumbled upon several examples where the geographic CRS does not start with "GCS" and the datum does not start with "D_". Is there a specific reason why the ESRI PE CRS catalog is not 100% consistent with the ESRI naming convention for CRSs and datums?

#### Examples:
- [RSAO13  EPSG:8699](https://epsg.org/crs_8699/[RSAO13](https://epsg.org/crs_8699/RSAO13.html?sessionkey=sjca4lrv0y).html?sessionkey=sjca4lrv0y)
![image](https://github.com/user-attachments/assets/896b91de-dcfe-43cd-9efd-ca1b10b9fd59)

  Here I would have expected ``GCS_RSAO13`` as the name of the geographic CRS and ``D_Reference_System_de_Angola_2013`` as the name of the datum. 

- The datum [Nouvelle Triangulation Francaise (Paris) EPSG:6807](https://equinor.georepository.com/datum_6807/Nouvelle-Triangulation-Francaise-Paris.html)
![image](https://github.com/user-attachments/assets/5f91edb1-ac81-4ccd-8552-90404d2d297e)

- [WGS 84 (G730) (EPSG:9053)](https://epsg.org/crs_9053/WGS-84-G730.html?sessionkey=ehi5n2wsyg)
![image](https://github.com/user-attachments/assets/b19f932b-352e-4a80-99d2-d38e7dc86f16)

**Comment by melitakennedy** [comment]
This is more ancient history of the projection engine library. And many of these 'oddities' are due to me and first developer who went along with it! The GCS_ and D_ prefixes arose out of my desire to be able to identify which object is being used or wanted if you have only the name. Similarly, working with various *nix operating systems, I really wanted names to have underscores--no pesky spaces! Stupid, now in retrospect. A few years back, the team decided to drop the GCS_ and D_ from the names, and internally, if you use the projection engine to compare objects, we ignore those prefixes and underscores within names.

**Comment by phaarnes** [comment]
Okay, I see. Thank you for a quick response Melita!
